### ISSUE TITLE
[BLOOD - CRYPTIC PASSAGE] Some doors will not open

### ISSUE THREAD

**Issue by duke912** [coelckers/Raze#199]
On the very first level of cryptic, just after you enter the first door that needs a key, there's a switch that opens a wall between 2 pillars, but hitting the switch will do nothing. On the second floor of the same room, there's also a door that doesn't open, making it not possible to continue the level.

[save0001.zip](https://github.com/coelckers/Raze/files/5604449/save0001.zip)

Save is looking at the 'glitched' switch.

I remember running through similar problems in the main game level 'Ghost Town' a few days ago, where some doors will not open, or open once/twice before become buggy, mainly the elevator where the Super Secret of that level is.

**Comment by sinisterseed** [comment]
Shoot, this is nasty.

I've also checked the elevator you mentioned on E3M1, and it doesn't open indeed. There's also a crazy HOM in that room.

That crack in the wall where the Fanatics were also cannot be blown up.

[brokenelevator.zip](https://github.com/coelckers/Raze/files/5604646/brokenelevator.zip)

![Blood_0000](https://user-images.githubusercontent.com/57503728/100385515-7c2d4280-302b-11eb-9744-44e6ec8909de.png)

**Comment by duke912** [comment]
Yep, a few minutes ago I could replicate the same bug in the second level of the first episode, just when you reach the station, you need to enter a booth to get a key, first time it opened fine but the cultist killed me, reloaded a save just before entering the station, but now the door will not open anymore, and not just that door, but any door inside the station.

**Comment by coelckers** [comment]
Can you please try to check if these problems only happen after reloading a savegame or also when the game runs normally.
The Blood save code has been redone recently and there may be a bug in there.

**Comment by sinisterseed** [comment]
Yeah, I think this is related to the save system.

I just replayed CP01 and E3M1 without saves and I encountered no soft locks and broken secrets. This also appears to be consistent with what duke just said above, how the doors initially worked, but then broke after a reload.

**Comment by duke912** [comment]
Just did a quick test and played the first level of CP without saving and both the switch and doors worked fine, but as soon as I quicksaved/reloaded then the bug just came back.

**Comment by sinisterseed** [comment]
Yep, that basically confirms it's a save issue.

**Comment by coelckers** [comment]
The non-opening doors should be fixed.
I'm not sure about the HOM glitch, that may still be present.
I also discovered one other problem: After saving the games some enemies stop their animation, after both loading and saving.

**Comment by coelckers** [comment]
Animations work again.
I'd still like a confirmation for the HOM, I wasn't able to reproduce it even with the bugged code so I'm not sure what's up there.

**Comment by sinisterseed** [comment]
The HOM is still there, the map is actually a HOM glitchfest for some reason.

It glitches upstairs/downstairs, at the second crack after the elevator, and the top of the elevator is also a disaster.

Otherwise, things seem to be in order gameplay wise. But I'm going to check more maps to be sure all's fine.

![Blood_0000](https://user-images.githubusercontent.com/57503728/100515550-aa269a00-3185-11eb-9235-ace6a9f3ffd3.png)
![Blood_0001](https://user-images.githubusercontent.com/57503728/100515552-aabf3080-3185-11eb-93ea-5db489e951c3.png)
![Blood_0002](https://user-images.githubusercontent.com/57503728/100515554-aabf3080-3185-11eb-9b35-ed1761327c9e.png)

[homfest.zip](https://github.com/coelckers/Raze/files/5610575/homfest.zip)

**Comment by sinisterseed** [comment]
I found out what's causing the HOMs, but made a new ticket for it to investigate since I'm not sure about what is its connection to this.

The HOMs appear when ending the game on a map (make sure you made a save on the respective map, this is required), starting another chapter, ending the game again, and loading the save you made on the other level.

After reload the ROR hackery will turn into a glitchfest.

**Comment by sinisterseed** [comment]
Also the softlock issues are not fully fixed.

Monster Bait from the base game makes an excellent map for testing these issues, and it breaks early on currently. If you fall into the river right at the start when the bridge collapses, there is a small elevator you can take back. The elevator itself still works, but the door never opens.

Additionally, after entering this room, the player is supposed to activate the two door switches, then press the one in the central panel to open the doors, but after pressing it the doors remain closed, rendering the map impossible to complete.

![Blood_0000](https://user-images.githubusercontent.com/57503728/100518018-a734a500-3197-11eb-95c7-192515760ef5.png)

There's also a puzzle at the very end of the map, and I have a feeling it's probably also broken, but can't attest that since I can't get to it legitimately, and noclipping will help with nothing here.

[broken monster bait.zip](https://github.com/coelckers/Raze/files/5610732/broken.monster.bait.zip)

**Comment by duke912** [comment]
I just did a test and was able to replicate the 'door not opening' bug in the end of 'Cradle to Grave' on both latest dev version and in the artifact from here:

https://github.com/coelckers/Raze/runs/1465828688

After you enter the last door leading to exit, if you save/reload there, you can't go back to explore the level.

**Comment by coelckers** [comment]
I hope it is fixed - it's hard to test because none of the screenshots have coordinate info.
Next time, please activate 'stat coord' before making a screenshot - that would simplify testing a lot because I could just use 'warptocoords'.

**Comment by sinisterseed** [comment]
> I hope it is fixed - it's hard to test because none of the screenshots have coordinate info.
> Next time, please activate 'stat coord' before making a screenshot - that would simplify testing a lot because I could just use 'warptocoords'.

You're kidding me, I hope.

What do you think the saves were for 😉 .

**Comment by coelckers** [comment]
The problems are because the saves are broken, they abort with an error in debug mode.

**Comment by sinisterseed** [comment]
Fair enough.

Sadly, this is take a while to re-test. The problem here is that we fix it, it works in a map, then it turns out it doesn't in another. The only way to be sure it works 100% is to basically replay the entire game using saves. That's not a 5 minute job, so this will stay open for the time being until it's confirmed for sure.

**Comment by duke912** [comment]
Just played the whole first episode with latest fix, and could not replicate the non-opening doors bug in any level, I'd say it's been fixed for good.

**Comment by sinisterseed** [comment]
We shall see, I'm on E2M3 now, and didn't nktice it so far.

But who knows, better safe than sorry.

**Comment by coelckers** [comment]
I think this can be closed now.

**Comment by sinisterseed** [comment]
Yes, I was about to mention this.

I've played the first e chapters in their entirety and checkdd all boss maps as well.

No more softlocks, unless a random, highly specific instance was missed somehow. But I've not encountered any anymore.
